### ISSUE TITLE
Error while trying to use "Additional listener" field

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-application-services-integration-iApp#25]
Trying to add additional listeners and got the following error:

'01020036:3: The requested virtual address (/Common/4.4.4%0) was not found.'

My inputs for additional listener were:
Virtual Server: Additional Listeners 
- Listener - 4.4.4.4
- Destination - 0 (pool index - I believe that's what its supposed to be but am not entirely sure)

I am also confused about the usage of this field, is it going to create multiple VS listening to the same port?

Thanks

**Comment by RafalKorepta** [comment]
We acknowledged the problem and we are working on it.

**Comment by 0xHiteshPatel** [comment]
Hi, 

Documentation for this field is here (along with all fields):
https://devcentral.f5.com/wiki/iApp.AppSvcsiApp_presoref.ashx#table-vs-listeners

I believe the issue you are seeing is caused because you are not specifying the port for the listener in the format <ip address>:<port> (example 4.4.4.4:1234)

Can you try correcting the input and deploying again?

**Comment by payalsin** [comment]
Hey Hitesh, thanks for the info. Yup providing ip:port format for the listener worked.
